spring:
  application:
    name: chat-app
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/simplyc}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
application:
  session:
    same-site: ${SESSION_SAME_SITE:None}
    token-ttl: ${SESSION_TOKEN_TTL:PT3H}
    refresh-token-ttl: ${SESSION_REFRESH_TOKEN_TTL:PT24H}
  otp:
    ttl: ${OTP_TTL:PT20M}
    email:
      api-key: ${EMAIL_API_KEY}
      api-url: ${EMAIL_API_URL:https://api.brevo.com/v3/smtp/email}
      from:
        email: ${EMAIL_FROM_ADDRESS:simplyc.bot@gmail.com}
  password-reset:
    token-ttl: ${PASSWORD_RESET_TOKEN_TTL:PT10M}
  upload:
    icons-dir: ${UPLOAD_ICONS_DIR:./upload/icons}
  websocket:
    relay-host: ${RABBITMQ_STOMP_HOST:localhost}
    relay-port: ${RABBITMQ_STOMP_PORT:61613}
    login: ${RABBITMQ_USERNAME:user}
    passcode: ${RABBITMQ_PASSWORD:password}
